### ISSUE TITLE
Difference from (main?) WikiPathways RDF

### ISSUE THREAD

**Issue by yayamamo** [wikipathways/SARS-CoV-2-WikiPathways#3]
Hi,

I cloned this repo. and loaded the RDF files into Apache Jena Fuseki at my local PC.
I issued a describe SPARQL query of `<http://identifiers.org/uniprot/Q9BYF1>` to both the local Fuseki and http://sparql.wikipathways.org/sparql .
There're some differences. For example, the local one has the following while the WikiPathways SPARQL endpoint doesn't.

`<http://rdf.wikipathways.org/Pathway/WP4846_r109431/WP/Interaction/id596b2488>`

On the other hand, the following is in the WikiPathways SPARQL EP, but the local one doesn't.

`<http://identifiers.org/wikipathways/WP2729_r101328>`

So, could you please let me know the difference?

Thanks.

**Comment by egonw** [comment]
The differences are because `http://sparql.wikipathways.org/sparql` is less frequently updated. You can see this is in the revision number `r101328` for the SPARQL endpoint and `r109431` for the GitHub repository. The revision number is derived from the WikiPathways MediaWiki software as increments with each WikiPathways edit (over the full wiki). But the higher the number, the newer the pathway,

**Comment by yayamamo** [comment]
I got it. Thank you.
